package net.avianlabs.solana.codegen

import kotlinx.serialization.json.Json
import net.avianlabs.solana.codegen.generator.ProgramGenerator
import net.avianlabs.solana.codegen.idl.RootNode
import java.io.File

val json = Json {
  ignoreUnknownKeys = true
  isLenient = true
}

fun main() {
  val idlDir = File("codegen/idl")
  val outputDir = File("solana-kotlin/src/commonMain/kotlin")

  require(idlDir.exists()) { "IDL directory not found: ${idlDir.absolutePath}" }
  require(outputDir.exists()) { "Output directory not found: ${outputDir.absolutePath}" }

  println("Reading IDL files from: ${idlDir.absolutePath}")
  println("Writing generated code to: ${outputDir.absolutePath}")

  val idlFiles = idlDir.listFiles { file -> file.extension == "json" }
    ?: error("Failed to list IDL files")

  idlFiles.forEach { idlFile ->
    println("\nProcessing: ${idlFile.name}")
    val idlText = idlFile.readText()
    val rootNode = json.decodeFromString<RootNode>(idlText)

    generateProgram(rootNode.program, outputDir)
    rootNode.additionalPrograms.forEach { generateProgram(it, outputDir) }

    println("  ✓ Generated ${rootNode.program.name}")
    if (rootNode.additionalPrograms.isNotEmpty()) {
      println("  ✓ Generated ${rootNode.additionalPrograms.size} additional program(s)")
    }
  }

  println("\n✓ Code generation complete!")
}

fun generateProgram(program: net.avianlabs.solana.codegen.idl.ProgramNode, outputDir: File) {
  val generator = ProgramGenerator(program)
  val fileSpec = generator.generate()

  val outputFile =
    outputDir.resolve("net/avianlabs/solana/domain/program/${program.name.toPascalCase()}Program.kt")
  outputFile.parentFile.mkdirs()

  val header = """// This code was AUTOGENERATED using Codama IDLs.
// Please DO NOT EDIT THIS FILE manually.
// Instead, update the IDL and regenerate using:
// ./gradlew :codegen:generateSolanaCode
//
// IDL source: codegen/idl/${program.name}.json

"""

  val generatedCode = StringBuilder()
  fileSpec.writeTo(generatedCode)

  outputFile.writeText(header + generatedCode.toString())
}

private fun String.toPascalCase(): String {
  return split('_', '-')
    .joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
}
