name: 'Main Branch Build'

concurrency:
  group: main
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  deployments: write
  checks: write
  statuses: write
  contents: write

jobs:
  build:
    name: Build Project
    runs-on: macos-14
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Run tests
        run: ./gradlew check

      - name: Bundle the failed build report
        if: failure()
        run: find ./build -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the failed build report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-report
          path: build-reports.zip
          retention-days: 7
